-- Generated by tools/build-rpc-sites.mjs — site CONFIG data, one module for every storefront.
RPC_SITES = {}

RPC_SITES["11st"] = {
  site = "11st",
  origin = "https://search.11st.co.kr",
  hosts = { "search.11st.co.kr" },
  search_url = "https://search.11st.co.kr/pc/total-search",
  search_param = "kwd",
  search_extra = { tabId = "TOTAL_SEARCH" },
  search_path_marker = "/pc/total-search",
  search_input_selector = 'input[type="search"]',
  -- The recommend rail renders the same c-card-item markup but links through an adoffice click
  -- redirect, so scope results to tiles that expose a real /products/ link.
  result_selector = 'li:has(a.c-card-item__anchor[href*="/products/"])',
  result_url_selector = 'a.c-card-item__anchor[href*="/products/"]',
  result_title_selector = '.c-card-item__name dd',
  result_image_selector = 'img[alt]',
  result_price_selector = '.c-card-item__price .value, .c-card-item__lowest .value',
  result_shipping_selector = '.c-card-item__price-delivery, .c-card-item__delivery',
  result_rating_selector = '.c-starrate, [aria-label*="평점"]',
  result_reviews_selector = '.c-starrate, [data-review-count]',
  result_delivery_selector = '.c-card-item__price-delivery, .c-card-item__delivery',
  result_ready_selector = 'li:has(a.c-card-item__anchor[href*="/products/"])',
  search_timeout = 6000,
  result_limit = 24,
  shipping_from_text = true,
  default_currency = "KRW",
  product_id_patterns = { "/products/(%d+)" },
  product_url_prefix = "https://www.11st.co.kr/products/",
  login_urls = { "/login", "login.11st.co.kr" },
  login_selector = 'form[action*="login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "비정상적인 접근", error = "access_denied" },
    { text = "보안 확인", error = "security_verification_required" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["ssg"] = {
  site = "ssg",
  origin = "https://www.ssg.com",
  hosts = { "ssg.com" },
  search_url = "https://www.ssg.com/search.ssg",
  search_param = "query",
  search_extra = { target = "all" },
  search_path_marker = "/search.ssg",
  search_input_selector = 'input[name="query"]',
  result_selector = 'li:has(a[href*="itemId="]), [data-react-unit-id][data-observable-item]',
  result_url_selector = 'a[href*="itemId="]',
  result_title_selector = '[data-info="prd_name"], .tx_ko, img[alt]',
  result_image_selector = 'img[alt]',
  result_price_selector = '.ssg_price, [data-info="price"]',
  result_shipping_selector = '.txt_delivery, .tx_deal, [data-info="delivery"]',
  result_rating_selector = '[aria-label*="평점"], .rate_bg',
  result_reviews_selector = '.rating_count, [data-info="review_count"]',
  result_delivery_selector = '.txt_delivery, .tx_deal, [data-info="delivery"]',
  result_ready_selector = 'li:has(a[href*="itemId="]), [data-observable-item]',
  search_timeout = 6000,
  result_limit = 24,
  default_currency = "KRW",
  product_id_patterns = { "[?&]itemId=([%w]+)" },
  product_url_prefix = "https://www.ssg.com/item/itemView.ssg?itemId=",
  login_urls = { "/login", "member.ssg.com" },
  login_selector = 'form[action*="login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "접속이 잠시 제한되었습니다", error = "access_denied" },
    { text = "자동화된 환경", error = "access_denied" },
    { text = "비정상적인 접근", error = "access_denied" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["coupang"] = {
  site = "coupang",
  origin = "https://www.coupang.com",
  hosts = { "coupang.com" },
  search_url = "https://www.coupang.com/np/search",
  search_param = "q",
  search_path_marker = "/np/search",
  search_input_selector = 'input[name="q"]',
  result_selector = 'li[data-id]:has(a[href*="/vp/products/"])',
  result_url_selector = 'a[href*="/vp/products/"]',
  result_title_selector = 'img[alt]',
  result_image_selector = 'img[alt]',
  result_shipping_selector = '[data-badge-type="feePrice"]',
  result_rating_selector = '[aria-label*="rating"]',
  result_ready_selector = 'li[data-id]:has(a[href*="/vp/products/"])',
  search_timeout = 6000,
  result_limit = 24,
  price_from_text = true,
  price_text_strategy = "last_before_shipping",
  shipping_from_text = true,
  default_currency = "KRW",
  product_id_patterns = { "/vp/products/(%d+)", "productId=(%d+)" },
  product_url_prefix = "https://www.coupang.com/vp/products/",
  login_urls = { "/login", "login.coupang.com" },
  login_selector = 'form[action*="login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"], .captcha', error = "captcha_required" }
  },
  blocked_text = {
    { text = "access denied", error = "access_denied" },
    { text = "비정상적인 접근", error = "access_denied" },
    { text = "자동화된 접근", error = "access_denied" }
  }
}

RPC_SITES["gmarket"] = {
  site = "gmarket",
  origin = "https://www.gmarket.co.kr",
  hosts = { "gmarket.co.kr" },
  search_url = "https://www.gmarket.co.kr/n/search",
  search_param = "keyword",
  search_path_marker = "/n/search",
  search_input_selector = 'input[name="keyword"]',
  -- data-montelena-goodscode only ever appears on nodes INSIDE a card, so matching it as a result
  -- root filled the read window with duplicates; the container is the one node per item and the
  -- product id comes from the item URL.
  result_selector = '.box__item-container',
  result_url_selector = 'a[href*="goodscode="], a[href*="goodsCode="]',
  result_title_selector = '.text__item, [data-montelena-acode="200003874"]',
  result_image_selector = 'img[alt]',
  result_price_selector = '.text__value, [data-price]',
  result_shipping_selector = '.box__delivery, .text__delivery',
  result_rating_selector = '.image__awards-points, [aria-label*="평점"]',
  result_reviews_selector = '.text__reviews, [data-review-count]',
  result_delivery_selector = '.box__delivery, .text__delivery',
  result_ready_selector = '.box__item-container .text__value',
  search_timeout = 6000,
  result_limit = 24,
  default_currency = "KRW",
  product_id_patterns = { "[?&]goodscode=(%d+)", "[?&]goodsCode=(%d+)" },
  product_url_prefix = "https://item.gmarket.co.kr/Item?goodscode=",
  login_urls = { "/login", "signin.gmarket" },
  login_selector = 'form[action*="login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="challenge"], iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "just a moment", error = "security_verification_required" },
    { text = "봇 확인 절차", error = "security_verification_required" },
    { text = "간단한 확인만 완료", error = "security_verification_required" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["walmart"] = {
  site = "walmart",
  origin = "https://www.walmart.com",
  hosts = { "walmart.com" },
  search_url = "https://www.walmart.com/search",
  search_param = "q",
  search_path_marker = "/search",
  search_input_selector = 'input[type="search"][name="q"]',
  result_selector = '[data-item-id][data-dca-id]',
  result_id_attr = "data-dca-id",
  result_url_selector = 'a[link-identifier][href*="/ip/"]',
  result_title_selector = '[data-automation-id="product-title"]',
  result_image_selector = 'img[data-testid="productTileImage"], img[alt]',
  -- The visible price node concatenates dollars and cents ("$1452"); the container's aria-label
  -- carries the decimal current price ("Price $ 14.52 Was $ 13.83 ...").
  result_price_selector = '[data-testid="unified-global-product-price"]',
  result_price_attr = "aria-label",
  result_shipping_selector = '[data-automation-id="fulfillment-badge"], [data-testid="fulfillment-speed"]',
  result_rating_selector = '[data-testid="product-ratings"]',
  result_reviews_selector = 'a[href*="#reviews"], [data-testid="product-reviews"]',
  result_delivery_selector = '[data-testid="fulfillment-speed"]',
  -- Ad/module wrappers carry [data-item-id][data-dca-id] before the product tiles hydrate, so
  -- readiness requires a tile that already exposes its price.
  result_ready_selector = '[data-item-id][data-dca-id] [data-testid="unified-global-product-price"], [data-testid="search-no-results"]',
  search_timeout = 6000,
  result_limit = 24,
  default_currency = "USD",
  product_id_patterns = { "/ip/[^/?]+/(%d+)", "/ip/(%d+)" },
  product_url_prefix = "https://www.walmart.com/ip/",
  login_urls = { "/account/login", "/account/verify" },
  login_selector = 'form[action*="/account/login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "robot or human", error = "captcha_required" },
    { text = "verify your identity", error = "security_verification_required" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["ebay"] = {
  site = "ebay",
  origin = "https://www.ebay.com",
  hosts = { "ebay.com" },
  search_url = "https://www.ebay.com/sch/i.html",
  search_param = "_nkw",
  search_path_marker = "/sch/i.html",
  search_input_selector = '#gh-ac, input[aria-label="Search for anything"]',
  -- eBay's search results render as `li.s-card` tiles carrying the listing id; the older
  -- `su-item-card` / `s-item` markup is gone. Shipping has no stable node, so it is parsed from the
  -- card text (shipping_from_text) where the "+배송비 …" / "shipping" fragment appears.
  result_selector = 'li.s-card[data-listingid]',
  result_id_attr = "data-listingid",
  result_url_selector = "a[href*='/itm/']",
  result_title_selector = '.s-card__title .su-styled-text, .s-card__title',
  result_image_selector = 'img[alt]',
  result_price_selector = '.s-card__price',
  result_condition_selector = '.s-card__subtitle',
  -- Readiness requires a tile that already carries its price, not just the results container.
  result_ready_selector = 'li.s-card[data-listingid] .s-card__price, .srp-save-null-search, #signin-main, #captcha_form',
  search_timeout = 6000,
  result_limit = 24,
  shipping_from_text = true,
  default_currency = "USD",
  product_id_patterns = { "/itm/(%d+)", "[?&]item=(%d+)" },
  product_url_prefix = "https://www.ebay.com/itm/",
  login_urls = { "signin.ebay.com", "/signin/" },
  login_selector = 'form#signin-form, #signin-main, input#userid, input#pass',
  blocked_selectors = {
    { selector = "#captcha_form, #captcha-box, form[action*='captcha'], input[name='captcha']", error = "captcha_required" }
  },
  blocked_text = {
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["aliexpress"] = {
  site = "aliexpress",
  origin = "https://ko.aliexpress.com",
  hosts = { "ko.aliexpress.com" },
  search_path_prefix = "https://ko.aliexpress.com/w/wholesale-",
  search_path_suffix = ".html",
  search_path_marker = "/w/wholesale-",
  search_input_selector = 'input[type="search"]',
  result_selector = 'a.search-card-item[href*="/item/"]',
  result_url_from_root = true,
  result_title_selector = 'img[alt]',
  result_image_selector = 'img[alt]',
  result_rating_selector = '[aria-label*="rating"], [aria-label*="Rating"]',
  result_reviews_selector = '[aria-label*="sold"], [aria-label*="orders"]',
  result_ready_selector = 'a.search-card-item[href*="/item/"], form[action*="captcha"]',
  search_timeout = 6000,
  result_limit = 24,
  price_from_text = true,
  shipping_from_text = true,
  product_id_patterns = { "/item/(%d+)" },
  product_url_prefix = "https://ko.aliexpress.com/item/",
  product_url_suffix = ".html",
  login_urls = { "/login", "login.aliexpress.com" },
  login_selector = 'form[action*="login"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"], #captcha', error = "captcha_required" }
  },
  blocked_text = {
    { text = "slide to verify", error = "captcha_required" },
    { text = "security verification", error = "security_verification_required" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["etsy"] = {
  site = "etsy",
  origin = "https://www.etsy.com",
  hosts = { "etsy.com" },
  search_url = "https://www.etsy.com/search",
  search_param = "q",
  search_path_marker = "/search",
  search_input_selector = 'input[name="search_query"]',
  -- data-listing-id repeats on nested nodes (card, link, favorite button, video), so the read
  -- window would fill with duplicates of the first few listings; keep only the outermost card.
  result_selector = '[data-listing-id]:not([data-listing-id] [data-listing-id])',
  result_id_attr = "data-listing-id",
  result_url_selector = 'a[href*="/listing/"]',
  result_title_selector = 'h3, [data-listing-card-title]',
  result_image_selector = 'img[alt]',
  result_price_selector = '.currency-value, [data-buy-box-region="price"]',
  result_shipping_selector = '[data-shipping-cost], [data-delivery-estimate]',
  result_rating_selector = '[aria-label*="out of 5 stars"]',
  result_reviews_selector = 'a[href*="#reviews"]',
  result_delivery_selector = '[data-delivery-estimate]',
  result_ready_selector = '[data-listing-id] .currency-value, iframe[src*="captcha"]',
  search_timeout = 6000,
  result_limit = 24,
  shipping_from_text = true,
  default_currency = "USD",
  product_id_patterns = { "/listing/(%d+)" },
  product_url_prefix = "https://www.etsy.com/listing/",
  login_urls = { "/signin" },
  login_selector = 'form[action*="signin"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "enable javascript and cookies to continue", error = "captcha_required" },
    { text = "verify you are human", error = "captcha_required" },
    { text = "access denied", error = "access_denied" }
  }
}

RPC_SITES["naver-shopping"] = {
  site = "naver-shopping",
  origin = "https://search.shopping.naver.com",
  hosts = { "search.shopping.naver.com" },
  search_url = "https://search.shopping.naver.com/search/all",
  search_param = "query",
  search_path_marker = "/search/",
  search_input_selector = 'input[type="search"]',
  result_selector = '[data-shp-contents-id]',
  result_id_attr = "data-shp-contents-id",
  result_url_selector = 'a[href*="/products/"], a[href*="/catalog/"]',
  result_title_selector = 'a[title], img[alt]',
  result_image_selector = 'img[alt]',
  result_rating_selector = '[aria-label*="평점"], [aria-label*="rating"]',
  result_reviews_selector = 'a[href*="review"], [data-review-count]',
  result_delivery_selector = '[data-delivery-info]',
  result_ready_selector = '[data-shp-contents-id], [data-testid="SEARCH_PRODUCT_LIST"]',
  search_timeout = 6000,
  result_limit = 24,
  price_from_text = true,
  shipping_from_text = true,
  default_currency = "KRW",
  product_id_patterns = { "/products/(%d+)", "/catalog/(%d+)" },
  login_urls = { "nidlogin.login" },
  login_selector = 'form[action*="nidlogin"] input[type="password"]',
  blocked_selectors = {
    { selector = 'iframe[src*="captcha"], form[action*="captcha"]', error = "captcha_required" }
  },
  blocked_text = {
    { text = "please complete the security verification", error = "security_verification_required" },
    { text = "보안 확인을 완료해 주세요", error = "security_verification_required" },
    { text = "실제 사용자인지 확인", error = "security_verification_required" },
    { text = "접속이 일시적으로 제한", error = "access_denied" },
    { text = "비정상적인 접근", error = "access_denied" },
    { text = "접근이 제한", error = "access_denied" }
  }
}
