-- GENERATED by tools/build-rpc-sites.mjs — do not edit.
--
-- Every value here is the site adapter's own registered config, taken whole. Nothing is selected,
-- so a key the adapter declares cannot be missing from the reader: three migration slices in a row
-- were fixed by copying a block that had been left behind.
RPC_SITES = {}
RPC_SITES["11st"] = {
  site = "11st",
  home_url = "https://www.11st.co.kr/",
  hosts = {
    "11st.co.kr"
  },
  search_url = "https://search.11st.co.kr/pc/total-search",
  search_param = "kwd",
  search_extra = {
    tabId = "TOTAL_SEARCH"
  },
  search_path_marker = "/pc/total-search",
  result_selector = "li.c-search-list__item, li:has(> .c-card-item)",
  result_url_selector = "a.c-card-item__anchor[href*=\"/products/\"]",
  result_id_selector = "a.c-card-item__anchor[data-log-body]",
  result_id_attr = "data-log-body",
  result_title_selector = ".c-card-item__name dd, img[alt]",
  result_image_selector = "img[alt]",
  result_price_selector = ".c-card-item__price .value, .c-card-item__lowest .value",
  result_shipping_selector = ".c-card-item__price-delivery, .c-card-item__price-delivery .value",
  result_rating_selector = ".c-starrate, [aria-label*=\"평점\"]",
  result_reviews_selector = ".c-starrate, [data-review-count]",
  result_delivery_selector = "dd.c-card-item__price-delivery",
  shipping_from_text = true,
  result_ready_selector = "li.c-search-list__item, li:has(> .c-card-item)",
  search_timeout = 5000,
  default_currency = "KRW",
  product_id_patterns = {
    "/products/(%d+)",
    "\"content_no\"%s*:%s*\"(%d+)\""
  },
  product_url_prefix = "https://www.11st.co.kr/products/",
  product_title_selectors = {
    "h1.title"
  },
  product_price_selectors = {
    "#finalDscPrcArea .value"
  },
  add_selectors = {
    "button.btn_cart[data-log-actionid-label=\"cart\"]"
  },
  quantity_selectors = {
    "input[name=\"quantity\"]",
    "select[name=\"quantity\"]"
  },
  required_option_selectors = {
    "select[required]"
  },
  cart_url = "https://buy.11st.co.kr/cart/CartAction.tmall?method=getCartList",
  cart_url_markers = {
    "buy.11st.co.kr/cart",
    "CartAction.tmall"
  },
  cart_item_scopes = {
    "li.s_cart_prd"
  },
  login_urls = {
    "/login",
    "login.11st.co.kr"
  },
  login_selector = "form[action*=\"login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "비정상적인 접근",
      error = "access_denied"
    },
    {
      text = "보안 확인",
      error = "security_verification_required"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}

RPC_SITES["aliexpress"] = {
  site = "aliexpress",
  home_url = "https://www.aliexpress.com/",
  hosts = {
    "aliexpress.com"
  },
  search_path_prefix = "https://www.aliexpress.com/w/wholesale-",
  search_path_suffix = ".html",
  search_path_marker = "/w/wholesale-",
  result_selector = "a.search-card-item[href*=\"/item/\"]",
  result_url_from_root = true,
  result_title_selector = "img[alt]",
  result_image_selector = "img[alt]",
  price_from_text = true,
  shipping_from_text = true,
  result_rating_selector = "[aria-label*=\"rating\"], [aria-label*=\"Rating\"]",
  result_reviews_selector = "[aria-label*=\"sold\"], [aria-label*=\"orders\"]",
  result_ready_selector = "a.search-card-item[href*=\"/item/\"], form[action*=\"captcha\"]",
  pagination = {
    mode = "query",
    param = "page",
    start = 1,
    step = 1,
    max_pages = 2
  },
  product_id_patterns = {
    "/item/(%d+)"
  },
  product_url_prefix = "https://www.aliexpress.com/item/",
  product_url_suffix = ".html",
  product_title_selectors = {
    "[data-pl=\"product-title\"] h1",
    "h1[data-pl=\"product-title\"]",
    "h1"
  },
  product_price_selectors = {
    "[data-pl=\"product-price\"]",
    "[data-testid=\"product-price\"]"
  },
  add_selectors = {
    "button[data-pl=\"add-to-cart\"]",
    "button[data-testid=\"add-to-cart\"]"
  },
  quantity_selectors = {
    "input[type=\"number\"]",
    "input[aria-label*=\"Quantity\"]"
  },
  required_option_selectors = {
    "select[required]"
  },
  confirmation_selector = "[data-pl=\"add-to-cart-success\"], [data-testid=\"add-to-cart-success\"]",
  confirmation_text_selectors = {
    "[data-pl=\"add-to-cart-success\"]",
    "[data-testid=\"add-to-cart-success\"]"
  },
  add_ready_selector = "[data-pl=\"add-to-cart-success\"], [data-testid=\"add-to-cart-success\"], form[action*=\"login\"], form[action*=\"captcha\"]",
  cart_url = "https://www.aliexpress.com/p/shoppingcart/index.html",
  cart_url_markers = {
    "/shoppingcart/",
    "/cart"
  },
  login_urls = {
    "/login",
    "login.aliexpress.com"
  },
  login_selector = "form[action*=\"login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"], #captcha",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "slide to verify",
      error = "captcha_required"
    },
    {
      text = "security verification",
      error = "security_verification_required"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}

RPC_SITES["amazon"] = {
  site = "amazon",
  home_url = "https://www.amazon.com/",
  hosts = {
    "www.amazon.com",
    "amazon.com"
  },
  search_url = "https://www.amazon.com/s",
  search_param = "k",
  search_path_marker = "/s",
  result_selector = "[data-component-type=\"s-search-result\"][data-asin]",
  result_ready_selector = "[data-component-type=\"s-search-result\"][data-asin], .s-no-results-result, #authportal-main-section, #ap_email, #ap_password, form[action*=\"validateCaptcha\"]",
  result_id_attr = "data-asin",
  result_url_selector = "h2 a, a.a-link-normal.s-no-outline, a[href*=\"/dp/\"], a[href*=\"/gp/product/\"]",
  result_title_selector = "a h2 span, a h2",
  result_image_selector = "img.s-image",
  result_price_selector = ".a-price .a-offscreen",
  result_shipping_selector = "[data-cy=\"delivery-block\"], [data-cy=\"delivery-recipe\"]",
  result_rating_selector = "i.a-icon-star-small span.a-icon-alt, .a-icon-alt",
  result_reviews_selector = "a[href*=\"#customerReviews\"] span, a[href*=\"#customerReviews\"]",
  result_limit = 24,
  default_currency = "USD",
  product_id_patterns = {
    "/dp/([A-Z0-9]+)",
    "/gp/product/([A-Z0-9]+)",
    "^([A-Z0-9]+)$"
  },
  product_url_prefix = "https://www.amazon.com/dp/",
  blocked_selectors = {
    {
      selector = "form[action*=\"validateCaptcha\"]",
      error = "captcha_required"
    }
  },
  login_selector = "#authportal-main-section, #ap_email, #ap_password",
  login_urls = {
    "/ap/signin"
  },
  product_title_selectors = {
    "span#productTitle",
    "#title span#productTitle",
    "h1#title"
  },
  product_price_selectors = {
    "#corePrice_feature_div .a-offscreen",
    ".priceToPay .a-offscreen",
    "#price_inside_buybox",
    "#apex_desktop .a-offscreen"
  },
  add_selectors = {
    "#add-to-cart-button",
    "input[name=\"submit.add-to-cart\"]",
    "#submit.add-to-cart input",
    "input[name=\"submit.addToCart\"]"
  },
  quantity_selectors = {
    "#quantity"
  },
  add_ready_selector = "#sw-atc-confirmation, #NATC_SMART_WAGON_CONF_MSG_SUCCESS, #huc-v2-order-row-confirm-text, #attach-warranty-pane:not(.aok-hidden), #authportal-main-section, #ap_email, #ap_password, form[action*=\"validateCaptcha\"]",
  confirmation_selector = "#sw-atc-confirmation, #NATC_SMART_WAGON_CONF_MSG_SUCCESS, #huc-v2-order-row-confirm-text",
  confirmation_text_selectors = {
    "#NATC_SMART_WAGON_CONF_MSG_SUCCESS",
    "#attachDisplayAddBaseAlert",
    "#attach-added-to-cart-message",
    "#huc-v2-order-row-confirm-text",
    "#sw-atc-confirmation",
    "#ewc-content"
  },
  upsell_pane_selector = "#attach-warranty-pane:not(.aok-hidden)",
  upsell_decline_selector = "#attach-warranty-pane:not(.aok-hidden) #attachSiNoCoverage input, #attach-warranty-pane:not(.aok-hidden) #attachSiNoCoverage .a-button-input, #attach-warranty-pane:not(.aok-hidden) #attachSiNoCoverage",
  cart_url = "https://www.amazon.com/gp/cart/view.html",
  cart_url_markers = {
    "/gp/cart/view.html",
    "/cart/view.html",
    "/cart?"
  },
  cart_item_scopes = {
    ".sc-list-item",
    "#sc-active-cart .sc-list-item"
  },
  cart_count_selectors = {
    "#nav-cart-count",
    "#sc-subtotal-label-activecart"
  },
  cart_ready_selector = "#sc-active-cart, .sc-list-item[data-asin], #sc-empty-cart, #sc-subtotal-label-activecart",
  cart_empty_selector = "#sc-empty-cart",
  cart_item_selector = ".sc-list-item[data-asin]",
  cart_subtotal_selectors = {
    "#sc-subtotal-amount-activecart",
    "#sc-subtotal-label-activecart"
  },
  checkout_button_selectors = {
    "input[name=\"proceedToRetailCheckout\"]",
    "#sc-buy-box-ptc-button input",
    "[data-feature-id=\"proceed-to-checkout-action\"] input",
    "#hlb-ptc-btn-native"
  },
  checkout_ready_selector = "#authportal-main-section, #ap_email, #ap_password, #submitOrderButtonId, #placeYourOrder, input[name=\"placeYourOrder1\"], #spc-orders, #subtotals, #deliver-to-customer-text, #checkout-payment-option-panel, form[action*=\"validateCaptcha\"]",
  checkout_url_markers = {
    "/gp/buy/",
    "/checkout/"
  },
  checkout_summary_selector = "#subtotals",
  checkout_delivering_to_selector = "#deliver-to-customer-text",
  checkout_address_selector = "#deliver-to-address-text",
  checkout_payment_selectors = {
    "#checkout-payment-option-panel",
    "#checkout-paymentOptionPanel"
  },
  place_order_selectors = {
    "#submitOrderButtonId",
    "input[name=\"placeYourOrder1\"]",
    "#bottomSubmitOrderButtonId"
  },
  product_timeout = 8000,
  pagination = {
    mode = "query",
    param = "page",
    start = 1,
    step = 1,
    max_pages = 2,
    next_selector = "a.s-pagination-next"
  }
}

RPC_SITES["coupang"] = {
  site = "coupang",
  home_url = "https://www.coupang.com/",
  hosts = {
    "coupang.com"
  },
  search_url = "https://www.coupang.com/np/search",
  search_param = "q",
  search_path_marker = "/np/search",
  result_selector = "li[data-id]:has(a[href*=\"/vp/products/\"])",
  result_url_selector = "a[href*=\"/vp/products/\"]",
  result_title_selector = "img[alt]",
  result_image_selector = "img[alt]",
  price_from_text = true,
  price_text_strategy = "last_before_shipping",
  result_shipping_selector = "[data-badge-type=\"feePrice\"]",
  shipping_from_text = true,
  result_ready_selector = "li[data-id]:has(a[href*=\"/vp/products/\"])",
  default_currency = "KRW",
  product_id_patterns = {
    "/vp/products/(%d+)",
    "productId=(%d+)"
  },
  product_url_prefix = "https://www.coupang.com/vp/products/",
  product_title_selectors = {
    "h2.prod-buy-header__title",
    "h1[data-product-title]",
    "h1"
  },
  product_price_selectors = {
    ".total-price strong",
    ".prod-sale-price .total-price",
    "[data-product-price]"
  },
  add_selectors = {
    "button.prod-cart-btn",
    "button[data-button-name=\"add-to-cart\"]"
  },
  quantity_selectors = {
    "select.prod-quantity__input",
    "input[name=\"quantity\"]"
  },
  required_option_selectors = {
    "select[required]"
  },
  confirmation_selector = ".cart-message",
  confirmation_text_selectors = {
    ".cart-message",
    ".prod-atf-notice"
  },
  add_ready_selector = ".cart-message, [data-cart-item-id], form[action*=\"login\"], .captcha",
  cart_url = "https://cart.coupang.com/cartView.pang",
  cart_url_markers = {
    "cartView.pang",
    "/cart"
  },
  cart_item_scopes = {
    "[id^=\"item_\"]"
  },
  login_urls = {
    "/login",
    "login.coupang.com"
  },
  login_selector = "form[action*=\"login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"], .captcha",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "access denied",
      error = "access_denied"
    },
    {
      text = "비정상적인 접근",
      error = "access_denied"
    },
    {
      text = "자동화된 접근",
      error = "access_denied"
    }
  }
}

RPC_SITES["ebay"] = {
  site = "ebay",
  home_url = "https://www.ebay.com/",
  hosts = {
    "www.ebay.com",
    "ebay.com"
  },
  search_url = "https://www.ebay.com/sch/i.html",
  search_param = "_nkw",
  search_path_marker = "/sch/",
  result_selector = "li.s-card[data-listingid], .su-item-card[data-view], .s-item-card[data-view]",
  result_id_attr = "data-listingid",
  result_ready_selector = "li.s-card, .srp-river-results, .srp-results, .su-item-card, .srp-save-null-search, #signin-main, #captcha_form",
  result_url_selector = "a[href*='/itm/'], .su-link.su-item-card__title, .su-item-card__title",
  result_title_selector = ".s-card__title, .su-item-card__title .su-styled-text, .su-item-card__title",
  result_image_selector = ".s-card__image, img.s-item__image-img, .su-card-container__media img, img",
  result_price_selector = ".s-card__price, .su-item-card__price, .s-item__price",
  result_shipping_selector = ".s-card__attribute-row, .su-card-container__attributes__primary, .s-item__details",
  result_condition_selector = ".s-card__subtitle, .su-item-card__subtitle .secondary, .su-item-card__header .secondary, .SECONDARY_INFO",
  result_seller_selector = ".s-card__caption, .su-card-container__attributes__secondary, .s-item__seller-info-text",
  result_limit = 24,
  default_currency = "USD",
  product_id_patterns = {
    "/itm/(%d+)"
  },
  product_url_prefix = "https://www.ebay.com/itm/",
  product_title_selectors = {
    "h1.x-item-title__mainTitle",
    ".x-item-title__mainTitle"
  },
  product_price_selectors = {
    ".x-price-primary",
    ".x-bin-price__content"
  },
  product_price_approx_selectors = {
    ".x-price-approx__price"
  },
  add_selectors = {
    "#atcBtn_btn_1",
    "[id^='atcBtn']",
    ".x-atc-action a"
  },
  cart_url = "https://cart.ebay.com/",
  cart_url_markers = {
    "cart.ebay.com"
  },
  cart_item_scopes = {
    "[data-test-id=\"cart-bucket\"]"
  },
  cart_count_selectors = {
    ".gh-cart .gh-badge",
    ".gh-cart__icon .badge"
  },
  cart_ready_selector = "[data-test-id='app-cart']",
  cart_item_selector = "[data-test-id='cart-item-link']",
  cart_empty_selector = "[data-test-id='start-shopping']",
  blocked_selectors = {
    {
      selector = "#captcha_form, #captcha-box, form[action*='captcha'], input[name='captcha']",
      error = "captcha_required"
    }
  },
  login_selector = "form#signin-form, #signin-main, input#userid, input#pass",
  login_urls = {
    "/signin"
  },
  pagination = {
    mode = "query",
    param = "_pgn",
    start = 1,
    step = 1,
    max_pages = 2,
    next_selector = "a[type=\"next\"], a.pagination__next"
  }
}

RPC_SITES["etsy"] = {
  site = "etsy",
  home_url = "https://www.etsy.com/",
  hosts = {
    "etsy.com"
  },
  search_url = "https://www.etsy.com/search",
  search_param = "q",
  search_path_marker = "/search",
  result_selector = "[data-listing-id]",
  result_id_attr = "data-listing-id",
  result_url_selector = "a[href*=\"/listing/\"]",
  result_title_selector = "h3, [data-listing-card-title]",
  result_image_selector = "img[alt]",
  result_price_selector = ".currency-value, [data-buy-box-region=\"price\"]",
  result_shipping_selector = "[data-shipping-cost], [data-delivery-estimate]",
  result_rating_selector = "[aria-label*=\"out of 5 stars\"]",
  result_reviews_selector = "a[href*=\"#reviews\"]",
  result_delivery_selector = "[data-delivery-estimate]",
  shipping_from_text = true,
  result_ready_selector = "[data-listing-id], iframe[src*=\"captcha\"]",
  default_currency = "USD",
  product_id_patterns = {
    "/listing/(%d+)"
  },
  product_url_prefix = "https://www.etsy.com/listing/",
  product_title_selectors = {
    "h1[data-buy-box-listing-title]",
    "h1"
  },
  product_price_selectors = {
    "[data-buy-box-region=\"price\"] .currency-value",
    "[data-buy-box-region=\"price\"]"
  },
  add_selectors = {
    "#listing-page-cart button[type=\"submit\"]",
    "[data-buy-box] form[action*=\"/cart/listing.php\"] button[type=\"submit\"]"
  },
  quantity_selectors = {
    "select[name=\"quantity\"]"
  },
  required_option_selectors = {
    "[id^=\"variation-selector-\"]",
    "[id^=\"perso-dropdown-\"]"
  },
  confirmation_selector = "[data-add-to-cart-success]",
  confirmation_text_selectors = {
    "[data-add-to-cart-success]"
  },
  add_ready_selector = "[data-add-to-cart-success], [data-cart-listing-id], form[action*=\"signin\"], iframe[src*=\"captcha\"]",
  cart_url = "https://www.etsy.com/cart",
  cart_url_markers = {
    "/cart"
  },
  cart_empty_phrases = {
    "your cart is empty"
  },
  login_urls = {
    "/signin"
  },
  login_selector = "form[action*=\"signin\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "enable javascript and cookies to continue",
      error = "captcha_required"
    },
    {
      text = "verify you are human",
      error = "captcha_required"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}

RPC_SITES["gmarket"] = {
  site = "gmarket",
  home_url = "https://www.gmarket.co.kr/",
  hosts = {
    "gmarket.co.kr"
  },
  search_url = "https://www.gmarket.co.kr/n/search",
  search_param = "keyword",
  search_path_marker = "/n/search",
  result_selector = ".box__item-container, [data-montelena-goodscode]",
  result_id_attr = "data-montelena-goodscode",
  result_url_selector = "a[href*=\"goodscode=\"], a[href*=\"goodsCode=\"]",
  result_title_selector = ".text__item, [data-montelena-acode=\"200003874\"]",
  result_image_selector = "img[alt]",
  result_price_selector = ".text__value, [data-price]",
  result_shipping_selector = ".box__delivery, .text__delivery",
  result_rating_selector = ".image__awards-points, [aria-label*=\"평점\"]",
  result_reviews_selector = ".text__reviews, [data-review-count]",
  result_delivery_selector = ".box__delivery, .text__delivery",
  result_ready_selector = ".box__item-container, [data-montelena-goodscode]",
  default_currency = "KRW",
  product_id_patterns = {
    "[?&]goodscode=(%d+)",
    "[?&]goodsCode=(%d+)"
  },
  product_url_prefix = "https://item.gmarket.co.kr/Item?goodscode=",
  product_title_selectors = {
    "h1.itemtit",
    "h1"
  },
  product_price_selectors = {
    ".price_real",
    ".price_innerwrap strong",
    "[data-price]"
  },
  add_selectors = {
    "#btn_add_cart",
    "button.button__add-cart",
    ".btn_mycart",
    "button[data-montelena-acode=\"200000911\"]"
  },
  quantity_selectors = {
    "input[name=\"orderQty\"]",
    "select[name=\"quantity\"]"
  },
  required_option_selectors = {
    "select[required]"
  },
  confirmation_selector = "[data-cart-layer=\"success\"], .box__layer-cart.is-active",
  confirmation_text_selectors = {
    "[data-cart-layer=\"success\"]",
    ".box__layer-cart.is-active"
  },
  add_ready_selector = "[data-cart-layer=\"success\"], .box__layer-cart.is-active, form[action*=\"login\"]",
  cart_url = "https://cart.gmarket.co.kr/ko/cart",
  cart_url_markers = {
    "cart.gmarket.co.kr",
    "/cart"
  },
  login_urls = {
    "/login",
    "signin.gmarket"
  },
  login_selector = "form[action*=\"login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"challenge\"], iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "just a moment",
      error = "security_verification_required"
    },
    {
      text = "봇 확인 절차",
      error = "security_verification_required"
    },
    {
      text = "간단한 확인만 완료",
      error = "security_verification_required"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}

RPC_SITES["naver-shopping"] = {
  site = "naver-shopping",
  home_url = "https://search.shopping.naver.com/search/all?query=%EC%87%BC%ED%95%91",
  hosts = {
    "shopping.naver.com",
    "search.shopping.naver.com"
  },
  search_url = "https://search.shopping.naver.com/search/all",
  search_param = "query",
  search_path_marker = "/search/",
  result_selector = "[data-shp-contents-id]:not([data-shp-contents-id] [data-shp-contents-id])",
  result_url_selector = "a[href*=\"cr.shopping.naver.com\"], a[href*=\"/products/\"], a[href*=\"/catalog/\"]",
  result_title_selector = "a[title], img[alt]",
  result_image_selector = "img[alt]",
  price_from_text = true,
  shipping_from_text = true,
  result_rating_selector = "[aria-label*=\"평점\"], [aria-label*=\"rating\"]",
  result_reviews_selector = "a[href*=\"review\"], [data-review-count]",
  result_delivery_selector = "[data-delivery-info]",
  result_ready_selector = "[data-shp-contents-id], [data-testid=\"SEARCH_PRODUCT_LIST\"]",
  prefer_embedded = true,
  embedded_json_selector = "script#__NEXT_DATA__",
  embedded_item_key = "mallProductId",
  embedded_fields = {
    url = {
      "crUrl"
    },
    title = {
      "productTitle",
      "productName"
    },
    image_alt = {
      "productTitle",
      "productName"
    },
    brand = {
      "maker"
    },
    image_url = {
      "imageUrl"
    },
    price_text = {
      "price",
      "lowPrice"
    },
    shipping_text = {
      "dlvryFee"
    },
    rating_text = {
      "scoreInfo"
    },
    reviews_text = {
      "reviewCount"
    }
  },
  default_currency = "KRW",
  product_id_patterns = {
    "/products/(%d+)",
    "/catalog/(%d+)"
  },
  cart_supported = false,
  product_title_selectors = {
    "h1"
  },
  product_price_selectors = {
    "[data-price]"
  },
  login_urls = {
    "nidlogin.login"
  },
  login_selector = "form[action*=\"nidlogin\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "please complete the security verification",
      error = "security_verification_required"
    },
    {
      text = "보안 확인을 완료해 주세요",
      error = "security_verification_required"
    },
    {
      text = "실제 사용자인지 확인",
      error = "security_verification_required"
    },
    {
      text = "접속이 일시적으로 제한",
      error = "access_denied"
    },
    {
      text = "비정상적인 접근",
      error = "access_denied"
    },
    {
      text = "접근이 제한",
      error = "access_denied"
    }
  }
}

RPC_SITES["ssg"] = {
  site = "ssg",
  home_url = "https://www.ssg.com/",
  hosts = {
    "ssg.com"
  },
  search_url = "https://www.ssg.com/search.ssg",
  search_param = "query",
  search_extra = {
    target = "all"
  },
  search_path_marker = "/search.ssg",
  result_selector = "div:has(> a[href*=\"itemId=\"])",
  result_url_selector = "a[href*=\"itemId=\"]",
  result_title_selector = "img[alt]",
  result_image_selector = "img[alt]",
  price_from_text = true,
  price_text_strategy = "last_before_shipping",
  shipping_from_text = true,
  result_ready_selector = "div:has(> a[href*=\"itemId=\"])",
  pagination = {
    mode = "query",
    param = "page",
    start = 1,
    step = 1,
    max_pages = 2
  },
  prefer_embedded = true,
  embedded_json_selector = "script#__NEXT_DATA__",
  embedded_item_key = "itemId",
  embedded_fields = {
    url = {
      "itemUrl"
    },
    title = {
      "itemName"
    },
    image_alt = {
      "itemName"
    },
    brand = {
      "brandName"
    },
    image_url = {
      "itemImgUrl"
    },
    price_text = {
      "rawPrimaryPrice",
      "primaryPrice"
    },
    rating_text = {
      "reviewScore"
    },
    reviews_text = {
      "reviewCount"
    }
  },
  default_currency = "KRW",
  product_id_patterns = {
    "[?&]itemId=([%w]+)"
  },
  product_url_prefix = "https://www.ssg.com/item/itemView.ssg?itemId=",
  product_title_selectors = {
    ".cdtl_info_tit h2",
    "h1"
  },
  product_price_selectors = {
    ".cdtl_new_price .ssg_price",
    ".ssg_price"
  },
  add_selectors = {
    "#actionCart",
    "#_bar_actionCart"
  },
  quantity_selectors = {
    "select[name=\"quantity\"]",
    "input[name=\"quantity\"]"
  },
  required_option_selectors = {
    "select[required]"
  },
  add_ready_selector = "form[action*=\"login\"], iframe[src*=\"captcha\"]",
  cart_url = "https://pay.ssg.com/cart/dmsShpp.ssg",
  cart_url_markers = {
    "pay.ssg.com/cart",
    "/cart/"
  },
  cart_empty_phrases = {
    "장바구니에 담긴 상품이 없습니다"
  },
  login_urls = {
    "/login",
    "member.ssg.com"
  },
  login_selector = "form[action*=\"login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "접속이 잠시 제한되었습니다",
      error = "access_denied"
    },
    {
      text = "자동화된 환경",
      error = "access_denied"
    },
    {
      text = "비정상적인 접근",
      error = "access_denied"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}

RPC_SITES["walmart"] = {
  site = "walmart",
  home_url = "https://www.walmart.com/",
  hosts = {
    "walmart.com"
  },
  search_url = "https://www.walmart.com/search",
  search_param = "q",
  search_path_marker = "/search",
  result_selector = "[data-item-id][data-dca-id]",
  result_id_attr = "data-dca-id",
  result_url_selector = "a[link-identifier][href*=\"/ip/\"]",
  result_title_selector = "[data-automation-id=\"product-title\"]",
  result_image_selector = "img[data-testid=\"productTileImage\"], img[alt]",
  result_price_selector = "[data-automation-id=\"ugpp-main-price\"], [data-automation-id=\"unified-global-product-price\"], [data-automation-id=\"product-price\"]",
  price_text_strategy = "decimal_preferred",
  result_shipping_selector = "[data-automation-id=\"fulfillment-badge\"], [data-testid=\"fulfillment-speed\"]",
  result_rating_selector = "[data-testid=\"product-ratings\"]",
  result_reviews_selector = "a[href*=\"#reviews\"], [data-testid=\"product-reviews\"]",
  result_delivery_selector = "[data-testid=\"fulfillment-speed\"]",
  result_ready_selector = "[data-item-id][data-dca-id], [data-testid=\"search-no-results\"]",
  pagination = {
    mode = "query",
    param = "page",
    start = 1,
    step = 1,
    max_pages = 2
  },
  default_currency = "USD",
  product_id_patterns = {
    "/ip/[^/?]+/(%d+)",
    "/ip/(%d+)"
  },
  product_url_prefix = "https://www.walmart.com/ip/",
  product_title_selectors = {
    "h1[itemprop=\"name\"]",
    "[data-testid=\"product-title\"]"
  },
  product_price_selectors = {
    "[itemprop=\"price\"][data-seo-id=\"hero-price\"]",
    "[data-testid=\"price-wrap\"] [itemprop=\"price\"]"
  },
  add_selectors = {
    "main button[data-automation-id=\"atc\"]",
    "button[data-automation-id=\"atc\"]"
  },
  quantity_selectors = {
    "select[id*=\"quantity\"]",
    "select[aria-label*=\"Quantity\"]"
  },
  confirmation_selector = "[data-testid=\"add-to-cart-success\"]",
  confirmation_text_selectors = {
    "[data-testid=\"add-to-cart-success\"]"
  },
  add_ready_selector = "[data-testid=\"add-to-cart-success\"], [data-testid=\"cart-drawer\"], form[action*=\"login\"]",
  cart_url = "https://www.walmart.com/cart",
  cart_url_markers = {
    "/cart"
  },
  cart_item_scopes = {
    "[data-testid=\"product-tile-container\"]"
  },
  login_urls = {
    "/account/login",
    "/account/verify"
  },
  login_selector = "form[action*=\"/account/login\"] input[type=\"password\"]",
  blocked_selectors = {
    {
      selector = "iframe[src*=\"captcha\"], form[action*=\"captcha\"]",
      error = "captcha_required"
    }
  },
  blocked_text = {
    {
      text = "robot or human",
      error = "captcha_required"
    },
    {
      text = "verify your identity",
      error = "security_verification_required"
    },
    {
      text = "access denied",
      error = "access_denied"
    }
  }
}
