#!/usr/bin/env node
// Merge each layer's Lua scripts into a single Lua file.
//
// The AXSDK extension loads Lua per directory in filename order: the shared base in
// `_common/scripts/*` first (it sets the `AX_BASE` global), then each `<site>/scripts/*`
// (which build on `AX_BASE` and expose `AX_<SITE>` / `AX_*` commands). This tool
// concatenates each directory's `*.lua` (sorted by filename) into one file:
//
//   dist/_common.lua   <- _common/scripts/*.lua
//   dist/<site>.lua    <- <site>/scripts/*.lua      (site-only; load AFTER _common.lua)
//
// With --self-contained each dist/<site>.lua is prefixed with _common so it runs alone.
//
// Each source file is wrapped in an immediately-invoked vararg function so per-file
// locals and any top-level `return` stay file-scoped — faithful to the runtime loading
// each file as its own chunk. Cross-file communication is via globals only (AX_BASE,
// AX_THUMBTACK, ...), which the wrapper preserves. A Lua chunk is compiled as a vararg
// function body, so wrapping a valid chunk as a function body is always valid Lua.
//
// Usage:
//   node tools/merge-lua.mjs [--out=dist] [--self-contained] [--no-common] [--check]
//   npm run build:lua
//   npm run build:lua:self-contained

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const COMMON = '_common';
const EXCLUDE = new Set(['node_modules', 'dist', 'tools', '.git']);

function parseArgs(argv) {
  const opts = { out: 'dist', selfContained: false, emitCommon: true, check: false, help: false };
  for (const a of argv) {
    if (a.startsWith('--out=')) opts.out = a.slice('--out='.length);
    else if (a === '--self-contained') opts.selfContained = true;
    else if (a === '--no-common') opts.emitCommon = false;
    else if (a === '--check' || a === '--dry-run') opts.check = true;
    else if (a === '-h' || a === '--help') opts.help = true;
    else throw new Error(`Unknown argument: ${a} (try --help)`);
  }
  return opts;
}

// A top-level dir is a "layer" when it has a scripts/ subdir containing >=1 .lua file.
function discoverLayers() {
  const layers = [];
  for (const name of readdirSync(repoRoot).sort()) {
    if (name.startsWith('.') || EXCLUDE.has(name)) continue;
    const scriptsDir = join(repoRoot, name, 'scripts');
    if (!existsSync(scriptsDir) || !statSync(scriptsDir).isDirectory()) continue;
    if (luaFiles(name).length) layers.push(name);
  }
  return layers;
}

// Repo-relative posix paths of a layer's *.lua, sorted by filename (= runtime load order).
function luaFiles(layer) {
  return readdirSync(join(repoRoot, layer, 'scripts'))
    .filter((f) => f.endsWith('.lua'))
    .sort()
    .map((f) => `${layer}/scripts/${f}`);
}

function wrap(relPath) {
  const raw = readFileSync(join(repoRoot, relPath), 'utf8').replace(/\r\n/g, '\n');
  const src = raw.replace(/\s+$/, '') + '\n'; // exactly one trailing newline before `end`
  // `;` after the call keeps statement boundaries unambiguous across concatenated IIFEs
  // (valid in Lua 5.1+; avoids `f()(...)` mis-parse with the next block).
  return `-- ===== ${relPath} =====\n(function(...)\n${src}end)(...);\n`;
}

function buildBundle(name, relPaths) {
  const header =
    `-- AUTO-GENERATED by tools/merge-lua.mjs — DO NOT EDIT.\n` +
    `-- Bundle: ${name}\n` +
    `-- Sources (load order):\n` +
    relPaths.map((p) => `--   ${p}`).join('\n') + '\n' +
    `-- Each source is wrapped in an immediately-invoked vararg function; cross-file\n` +
    `-- communication is via globals (AX_BASE, AX_<SITE>, AX_*).\n\n`;
  return header + relPaths.map(wrap).join('\n');
}

function printHelp() {
  console.log(`merge-lua — concatenate each layer's Lua into one file.

Usage: node tools/merge-lua.mjs [options]
  --out=DIR          output directory (default: dist)
  --self-contained   prepend _common into each site bundle (single-file per site)
  --no-common        do not emit the standalone dist/_common.lua
  --check            dry run; report what would be written, write nothing
  -h, --help         show this help`);
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) { printHelp(); return; }

  const layers = discoverLayers();
  const hasCommon = layers.includes(COMMON);
  const sites = layers.filter((l) => l !== COMMON);
  const commonFiles = hasCommon ? luaFiles(COMMON) : [];

  const outDir = resolve(repoRoot, opts.out);
  const outRel = relative(repoRoot, outDir) || '.';
  const outputs = [];

  if (hasCommon && opts.emitCommon) {
    outputs.push({ file: '_common.lua', label: '_common (base)', content: buildBundle('_common (base)', commonFiles) });
  }
  for (const site of sites) {
    const siteFiles = luaFiles(site);
    const relPaths = opts.selfContained ? [...commonFiles, ...siteFiles] : siteFiles;
    const label = opts.selfContained
      ? `${site} (self-contained: _common + ${site})`
      : `${site} (site-only; load after _common.lua)`;
    outputs.push({ file: `${site}.lua`, label, content: buildBundle(label, relPaths) });
  }

  if (!outputs.length) { console.error('merge-lua: no Lua layers found under ' + repoRoot); process.exit(1); }

  if (!opts.check) mkdirSync(outDir, { recursive: true });
  console.log(`${opts.check ? '[check] ' : ''}merge-lua -> ${outRel}/${opts.selfContained ? '  (self-contained)' : ''}`);
  for (const o of outputs) {
    if (!opts.check) writeFileSync(join(outDir, o.file), o.content);
    const lines = o.content.split('\n').length - 1;
    const kb = (Buffer.byteLength(o.content, 'utf8') / 1024).toFixed(1);
    console.log(`  ${opts.check ? 'would write' : 'wrote'} ${outRel}/${o.file}  (${lines} lines, ${kb} KB)  <- ${o.label}`);
  }
}

main();
